include:
  - path:
      - infra.yaml
services:
  db-migration:
    build:
      context: db
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: ./db/migration
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      dockerfile: Dockerfile.api
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./apps/api/
        - action: rebuild
          path: ./libs/
    ports:
      - "8080:3000"
    environment:
      - "API_PORT=3000"
      - "REDIS_HOST=redis"
      - "KAFKA_HOST=kafka"
      - "KAFKA_PORT=9094"
      - "ENABLE_DEV_CORS=true"
      - "KAFKAJS_NO_PARTITIONER_WARNING=0"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  solver:
    build:
      dockerfile: Dockerfile.solver
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./apps/solver/
        - action: rebuild
          path: ./libs/
    deploy:
      mode: replicated
      replicas: 1 # 2 doesn't seem to be stable
    environment:
      - "KAFKA_HOST=kafka"
      - "KAFKA_PORT=9094"
      - "KAFKAJS_NO_PARTITIONER_WARNING=0"
    depends_on:
      kafka:
        condition: service_healthy

  janitor:
    build:
      dockerfile: Dockerfile.janitor
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./apps/janitor/
        - action: rebuild
          path: ./libs/
    deploy:
      mode: replicated
      replicas: 1 # one and only one
    environment:
      - "JANITOR_PORT=3002"
