ALTER TABLE board DROP COLUMN cars;
ALTER TABLE board ALTER COLUMN h SET DEFAULT '';
ALTER TABLE board ALTER COLUMN h SET NOT NULL;
ALTER TABLE board ALTER COLUMN h SET DEFAULT '';
ALTER TABLE board ALTER COLUMN v SET NOT NULL;
